### PR TITLE
Elvijs/makefileisation

### PR DESCRIPTION
**Pull request by elvijs**
No changes to TF or GPflow. Just automating the environment setup and testing, so that we can proceed on a solid footing. Moved the automatic builds to GitHub actions.

One test was failing, but that doesn't look like a new addition. Skipping for now.

### CODE REVIEW

**Review by alexisboukouvalas — APPROVED** [review]
This looks awesome! Could you port these changes to the main repo?
You should have access now as I have invited you.
https://github.com/ManchesterBioinference/BranchedGP

**Comment by elvijs** [comment]
> This looks awesome! Could you port these changes to the main repo?
> You should have access now as I have invited you.
> https://github.com/ManchesterBioinference/BranchedGP

Sure thing, let me look at that this weekend! I also started the TF2/GPflow2 migration, I'll add you to the relevant PR.

**Comment by elvijs** [comment]
Actually, I forgot that I did black and pylint cleanup first, let me add you to that PR first - once you review, you can get on to the good stuff :P

**Comment by elvijs** [comment]
OK, I cannot seem to add you to that PR as you're not a contributor here. Here's the PR: https://github.com/elvijs/BranchedGP/pull/4.

**Pull request merged**
